services:
  portainer:
    image: portainer/portainer-ce:latest
    
    container_name: portainer
    restart: always
    ports:
      - '9000:9000'  # Porta para a interface web do Portainer
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - nginx_proxy

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/sdb1/stacks/portainer/data

networks:
  nginx_proxy:
    external: true