services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'    # Porta HTTP
      - '443:443'  # Porta HTTPS
      - '81:81'    # Interface de gerenciamento
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
      - nginx_geoip:/usr/share/GeoIP:ro
    networks:
      - nginx_proxy
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

volumes:
  nginx_data:
    name: nginx_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: #/pasta/nginx-proxy-manager/data

  nginx_letsencrypt:
    name: nginx_letsencrypt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: #/pasta/nginx-proxy-manager/letsencrypt

  nginx_geoip:
    name: nginx_geoip
    driver: local
    driver_opts:
      type: none
      o: bind
      device: #/pasta/nginx-proxy-manager/geoip

networks:
  nginx_proxy:
    external: true
