services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'    # Porta HTTP
      - '443:443'  # Porta HTTPS
      - '81:81'    # Interface de gerenciamento
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - nginx_proxy

volumes:
  npm_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: #/pasta/nginx-proxy-manager/data

  npm_letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: #/pasta/nginx-proxy-manager/letsencrypt

networks:
  nginx_proxy:
    external: true
